BlogPlayground/Models/Article.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BlogPlayground.Models
{
    public class Article
    {
        public int ArticleId { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Abstract { get; set; }
        [Required]
        public string Contents { get; set; }
        public DateTime CreatedDate { get; set; }

        //EF relationships should pick this relationship between Article and ApplicationUser tables: http://ef.readthedocs.io/en/latest/modeling/relationships.html     
        public string AuthorId { get; set; }
        public virtual ApplicationUser Author { get; set; }
    }
}

BlogPlayground/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogPlayground.Data;
using BlogPlayground.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using BlogPlayground.Services;

namespace BlogPlayground.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly IArticlesRepository _articlesRepository;
        private readonly IRequestUserProvider _requestUserProvider;

        public ArticlesController(IArticlesRepository articlesRepository, IRequestUserProvider requestUserProvider)
        {
            _articlesRepository = articlesRepository;
            _requestUserProvider = requestUserProvider;
        }

        // GET: Articles
        public async Task<IActionResult> Index()
        {
            return View(await _articlesRepository.GetAll());
        }

        // GET: Articles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _articlesRepository.GetOne(id.Value);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // GET: Articles/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Articles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Title, Abstract,Contents")] Article article)
        {
            if (ModelState.IsValid)
            {
                article.AuthorId = _requestUserProvider.GetUserId();
                article.CreatedDate = DateTime.Now;
                _articlesRepository.Add(article);
                await _articlesRepository.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(article);
        }

        // GET: Articles/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _articlesRepository.GetOne(id.Value);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // POST: Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var article = await _articlesRepository.GetOne(id);
            _articlesRepository.Remove(article);
            await _articlesRepository.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BlogPlayground/ViewComponents/LatestArticlesViewComponent.cs
using BlogPlayground.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogPlayground.ViewComponents
{
    public class LatestArticlesViewComponent: ViewComponent
    {
        private readonly IArticlesRepository _repository;

        public LatestArticlesViewComponent(IArticlesRepository repository)
        {
            _repository = repository;
        }

        public async Task<IViewComponentResult> InvokeAsync(int howMany = 2)
        {
            return View(await _repository.GetLatest(howMany));
        }
    }
}

BlogPlayground/Views/Articles/Create.cshtml
@model BlogPlayground.Models.Article

@{
    ViewData["Title"] = "Create";
}

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Create new article</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Abstract" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="Abstract" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Abstract" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Contents" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="Contents" class="form-control" rows="20"></textarea>
                <span asp-validation-for="Contents" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogPlayground/Views/Articles/Delete.cshtml
@model BlogPlayground.Models.Article

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Article</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Abstract)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Abstract)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Contents)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Contents)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

BlogPlayground/Views/Articles/Details.cshtml
@model BlogPlayground.Models.Article

@{
    ViewData["Title"] = Model.Title;
}

<div class="article-page container">
    <div class="col-md-8 article-details">
        @Html.Partial("_ArticleSummary", Model)
        <hr />
        <markdown source="@Model.Contents"></markdown>
    </div>

    <div class="col-md-4">
        <div class="container-fluid sidebar">
            <div class="row">
                <div class="btn-group">
                    <a asp-action="Create" class="btn btn-primary">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Write a new Article
                    </a>
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a asp-action="Index">Back to List</a></li>
                        <li><a asp-action="Delete" asp-route-id="@Model.ArticleId">Delete</a></li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <vc:latest-articles how-many="2"></vc:latest-articles>
            </div>
        </div>
    </div>

</div>

BlogPlayground/Views/Articles/Index.cshtml
@model IEnumerable<BlogPlayground.Models.Article>

@{
    ViewData["Title"] = "Articles";
}

<h3>This is what we have been writing...</h3>

<div class="container">
    <ul class="col-md-8 list-unstyled article-list">
    @foreach (var article in Model)
    {
        <li data-articleid="@article.ArticleId">
            @Html.Partial("_ArticleSummary", article)
        </li>
    }
    </ul>

    <div class="col-md-4">
        <div class="container-fluid sidebar">
            <div class="row">
                <a asp-action="Create" class="btn btn-primary">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Write a new Article
                </a>
            </div>
            <div class="row">
                <vc:latest-articles how-many="2"></vc:latest-articles>
            </div>
        </div>
    </div>

</div>

BlogPlayground/Views/Articles/_ArticleSummary.cshtml
@model BlogPlayground.Models.Article

<div class="row article-summary">
    <div class="col-md-4">
        <profile-picture profile="@Model.Author" size-px="40" />
        <p class="text-center author-name">
            @(Model.Author.FullName ?? Model.Author.UserName)
        </p>
        <p class="text-center">
            @Model.CreatedDate.ToString("dd MMM yyyy")
        </p>
    </div>
    <div class="col-md-8">
        <h4>
            <a asp-action="Details" asp-route-id="@Model.ArticleId">@Model.Title</a>
        </h4>
        <blockquote>
            <p>@Model.Abstract</p>
        </blockquote>
    </div>
</div>